apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: dataplatform
    user: datauser
    secureJsonData:
      password: mypassword
    jsonData:
      sslmode: prefer
      postgresVersion: 1300
      timescaledb: false
    isDefault: false
    editable: true
